import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1702153355957 implements MigrationInterface {
    name = 'Init1702153355957'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "historical_figure" DROP CONSTRAINT "historical_figure_state_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "battle" DROP CONSTRAINT "battle_war_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "city_state_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "historical_event_historical_figure" DROP CONSTRAINT "historical_event_historical_figure_historical_event_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "historical_event_historical_figure" DROP CONSTRAINT "historical_event_historical_figure_historical_figure_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reign" DROP CONSTRAINT "reign_ruler_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reign" DROP CONSTRAINT "reign_state_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "historical_event" DROP CONSTRAINT "historical_event_state_id_fkey"`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "username" character varying NOT NULL, "email" character varying NOT NULL, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "city_pkey"`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "state_id"`);
        await queryRunner.query(`ALTER TABLE "city" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "PK_b222f51ce26f7e5ca86944a6739" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "city" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" ADD "state_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" ADD "ruler_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "PK_b222f51ce26f7e5ca86944a6739"`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "PK_d699c964252d2a446f988eea045" PRIMARY KEY ("id", "ruler_id")`);
        await queryRunner.query(`ALTER TABLE "city" ADD "war_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "PK_d699c964252d2a446f988eea045"`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "PK_df0097201f1a2756a3682462011" PRIMARY KEY ("id", "ruler_id", "war_id")`);
        await queryRunner.query(`ALTER TABLE "city" ADD "established_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" ADD "current_existence" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" ADD "capital_city_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" ADD "start_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" ADD "end_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "PK_df0097201f1a2756a3682462011"`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "PK_782ce223ea8992ebeafa0e93611" PRIMARY KEY ("ruler_id", "war_id")`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "PK_df0097201f1a2756a3682462011"`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "PK_94ceb08c6e404aa6fe0215cd960" PRIMARY KEY ("war_id", "state_id")`);
        await queryRunner.query(`ALTER TABLE "historical_figure" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "historical_figure" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_figure" ALTER COLUMN "birth_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_figure" ALTER COLUMN "death_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_figure" DROP COLUMN "occupation"`);
        await queryRunner.query(`ALTER TABLE "historical_figure" ADD "occupation" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_figure" ALTER COLUMN "state_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_figure" DROP COLUMN "biography"`);
        await queryRunner.query(`ALTER TABLE "historical_figure" ADD "biography" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "battle" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "battle" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "battle" ALTER COLUMN "war_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "battle" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "battle" ADD "location" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "PK_146f7ba43141c256c9db494ced3"`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "PK_df0097201f1a2756a3682462011" PRIMARY KEY ("id", "ruler_id", "war_id")`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "historical_event_historical_figure_historical_event_id_seq" OWNED BY "historical_event_historical_figure"."historical_event_id"`);
        await queryRunner.query(`ALTER TABLE "historical_event_historical_figure" ALTER COLUMN "historical_event_id" SET DEFAULT nextval('"historical_event_historical_figure_historical_event_id_seq"')`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "historical_event_historical_figure_historical_figure_id_seq" OWNED BY "historical_event_historical_figure"."historical_figure_id"`);
        await queryRunner.query(`ALTER TABLE "historical_event_historical_figure" ALTER COLUMN "historical_figure_id" SET DEFAULT nextval('"historical_event_historical_figure_historical_figure_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "reign" ALTER COLUMN "ruler_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reign" ALTER COLUMN "state_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reign" ALTER COLUMN "end_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_event" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "historical_event" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_event" ALTER COLUMN "state_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_event" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "historical_event" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ruler" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "ruler" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ruler" ALTER COLUMN "birth_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ruler" ALTER COLUMN "death_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "PK_df0097201f1a2756a3682462011"`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "PK_146f7ba43141c256c9db494ced3" PRIMARY KEY ("id", "ruler_id", "war_id", "state_id")`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "city_state_id_seq" OWNED BY "city"."state_id"`);
        await queryRunner.query(`ALTER TABLE "city" ALTER COLUMN "state_id" SET DEFAULT nextval('"city_state_id_seq"')`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "city" ALTER COLUMN "state_id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "city_state_id_seq"`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "PK_146f7ba43141c256c9db494ced3"`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "PK_df0097201f1a2756a3682462011" PRIMARY KEY ("id", "ruler_id", "war_id")`);
        await queryRunner.query(`ALTER TABLE "ruler" ALTER COLUMN "death_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ruler" ALTER COLUMN "birth_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ruler" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "ruler" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_event" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "historical_event" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "historical_event" ALTER COLUMN "state_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_event" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "historical_event" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reign" ALTER COLUMN "end_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reign" ALTER COLUMN "state_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reign" ALTER COLUMN "ruler_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_event_historical_figure" ALTER COLUMN "historical_figure_id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "historical_event_historical_figure_historical_figure_id_seq"`);
        await queryRunner.query(`ALTER TABLE "historical_event_historical_figure" ALTER COLUMN "historical_event_id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "historical_event_historical_figure_historical_event_id_seq"`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "PK_df0097201f1a2756a3682462011"`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "PK_146f7ba43141c256c9db494ced3" PRIMARY KEY ("id", "state_id", "ruler_id", "war_id")`);
        await queryRunner.query(`ALTER TABLE "battle" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "battle" ADD "location" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "battle" ALTER COLUMN "war_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "battle" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "battle" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_figure" DROP COLUMN "biography"`);
        await queryRunner.query(`ALTER TABLE "historical_figure" ADD "biography" text`);
        await queryRunner.query(`ALTER TABLE "historical_figure" ALTER COLUMN "state_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_figure" DROP COLUMN "occupation"`);
        await queryRunner.query(`ALTER TABLE "historical_figure" ADD "occupation" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "historical_figure" ALTER COLUMN "death_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_figure" ALTER COLUMN "birth_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "historical_figure" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "historical_figure" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "PK_94ceb08c6e404aa6fe0215cd960"`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "PK_df0097201f1a2756a3682462011" PRIMARY KEY ("id", "ruler_id", "war_id")`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "PK_782ce223ea8992ebeafa0e93611"`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "PK_df0097201f1a2756a3682462011" PRIMARY KEY ("id", "ruler_id", "war_id")`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "capital_city_id"`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "current_existence"`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "established_date"`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "PK_df0097201f1a2756a3682462011"`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "PK_d699c964252d2a446f988eea045" PRIMARY KEY ("id", "ruler_id")`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "war_id"`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "PK_d699c964252d2a446f988eea045"`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "PK_b222f51ce26f7e5ca86944a6739" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "ruler_id"`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "state_id"`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "PK_b222f51ce26f7e5ca86944a6739"`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "city" ADD "state_id" integer`);
        await queryRunner.query(`ALTER TABLE "city" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "city_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`ALTER TABLE "historical_event" ADD CONSTRAINT "historical_event_state_id_fkey" FOREIGN KEY ("state_id") REFERENCES "state"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reign" ADD CONSTRAINT "reign_state_id_fkey" FOREIGN KEY ("state_id") REFERENCES "state"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reign" ADD CONSTRAINT "reign_ruler_id_fkey" FOREIGN KEY ("ruler_id") REFERENCES "ruler"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "historical_event_historical_figure" ADD CONSTRAINT "historical_event_historical_figure_historical_figure_id_fkey" FOREIGN KEY ("historical_figure_id") REFERENCES "historical_figure"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "historical_event_historical_figure" ADD CONSTRAINT "historical_event_historical_figure_historical_event_id_fkey" FOREIGN KEY ("historical_event_id") REFERENCES "historical_event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "city_state_id_fkey" FOREIGN KEY ("state_id") REFERENCES "state"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "battle" ADD CONSTRAINT "battle_war_id_fkey" FOREIGN KEY ("war_id") REFERENCES "war"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "historical_figure" ADD CONSTRAINT "historical_figure_state_id_fkey" FOREIGN KEY ("state_id") REFERENCES "state"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
